# const qrcodeSchema = new mongoose.Schema(
#   {
#     title: { type: String, default: "" },
#     url: { type: String, default: "" },
#   },
#   { timestamps: true }
# );

GET http://localhost:3000/api/qrcodes/66466e03e6cf1a03aa6c5021

###


POST https://next-api-bay-zeta.vercel.app/api/signup
Content-Type: application/json

{
  "name":"ss",
  "email":"cat1@naver.com",
  "password":"1234",
  "role":"student"
}
###

POST https://next-api-bay-zeta.vercel.app/api/login
Content-Type: application/json

{
  "email":"seokiis@naver.com",
  "password":"1234"
}
###

POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email":"cat1181123@naver.com",
  "password":"1234"
}
###
POST https://next-api-bay-zeta.vercel.app/api/login
Content-Type: application/json

{
  "email":"cat1181123@naver.com",
  "password":"1234"
}

###

GET http://localhost:3000/api/login

###
POST http://localhost:3000/api/users
Content-Type: application/json


{
  "email":"cat1181123@naver.com",
  "password":"1234"
}
ㅊ
###

GET http://localhost:3000/api/qrcodes
###

POST http://localhost:3000/api/qrcodes/
Content-Type: application/json

[
{
  "title":"post4",
  "url":"www.seokiis.com",
},
{
  "title":"post3",
  "url":"www.daum.net",
}
]
###
