# const qrcodeSchema = new mongoose.Schema(
#   {
#     title: { type: String, default: "" },
#     url: { type: String, default: "" },
#   },
#   { timestamps: true }
# );

GET http://localhost:3000/api/qrcodes/66466e03e6cf1a03aa6c5021

###

GET http://localhost:3000/api/qrcodes
###

POST http://localhost:3000/api/qrcodes/
Content-Type: application/json

[
{
  "title":"post4",
  "url":"www.seokiis.com"
},
{
  "title":"post3",
  "url":"www.daum.net"
}
]
###
